#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  30
yabai -m config bottom_padding               30
yabai -m config left_padding                 45
yabai -m config right_padding                45
yabai -m config window_gap                   5

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^QQ*" manage=off
yabai -m rule --add app="^Telegram$" manage=off
yabai -m rule --add app="^ClashX*" manage=off
yabai -m rule --add app="^JetBrains Toolbox" manage=off
yabai -m rule --add app="^Karabiner*" manage=off
yabai -m rule --add app="^KeyCastr$" manage=off
yabai -m rule --add app="^Min$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^AppCleaner$" manage=off
yabai -m rule --add app="^Activity*" manage=off
yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^Shottr$" manage=off
yabai -m rule --add app="^Kap$" manage=off
yabai -m rule --add app="^Speedtest$" manage=off
yabai -m rule --add app="^ffplay$" manage=off
yabai -m rule --add app="^pieces$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Preview$" manage=off

# space label
echo "yabai configuration loaded.."
